### DISCUSSION TITLE
Example: LMS Lyrion Music Server

### DISCUSSION THREAD

**Discussion by zecoj** [lovelylain/hass_ingress#36] [Show and tell]
https://registry.hub.docker.com/r/lmscommunity/lyrionmusicserver

Aside from tunein logo/covers, everything seems to work. Only tested with Material theme (non-party one). Fixes welcome.

```yaml
ingress:
  lms:
    ui_mode: toolbar
    title: Music
    icon: mdi:music
    url: http://x.x.x.x:9000
    rewrite:
      - mode: body
        match: 'href="/'
        replace: 'href="$http_x_ingress_path/'
      - mode: body
        match: 'src="/'
        replace: 'src="$http_x_ingress_path/'
      - mode: body
        match: 'srcset="/'
        replace: 'srcset="$http_x_ingress_path/'
      - mode: body
        match: 'srcset=/'
        replace: 'srcset=$http_x_ingress_path/'
      - mode: body
        match: 'action="/'
        replace: 'action="$http_x_ingress_path/'
      - mode: body
        match: 'webroot       = "/'
        replace: 'webroot       = "$http_x_ingress_path/'
      - mode: body
        match: 'navigationUrl = "/'
        replace: 'navigationUrl = "$http_x_ingress_path/'
      - mode: body
        match: "dataUrl: '/"
        replace: "dataUrl: '$http_x_ingress_path/"
      - mode: body
        match: 'location.replace\("/'
        replace: 'location.replace("$http_x_ingress_path/'
      - mode: body
        match: "BLANK_IMAGE_URL = '/"
        replace: "BLANK_IMAGE_URL = '$http_x_ingress_path/"
      - mode: body
        match: "SqueezeJS.Controller.getBaseUrl() + '/"
        replace: "SqueezeJS.Controller.getBaseUrl() + '$http_x_ingress_path/"
      - mode: body
        match: '/anyurl'
        replace: '$http_x_ingress_path/anyurl'
      - mode: body
        match: '/cometd'
        replace: '$http_x_ingress_path/cometd'
      - mode: body
        match: 'add("plugins")'
        replace: 'add("$http_x_ingress_path/plugins")'
      - mode: body
        match: '"plugins/'
        replace: '"$http_x_ingress_path/plugins/'
      - mode: body
        match: '"/plugins/'
        replace: '"$http_x_ingress_path/plugins/'
      - mode: body
        match: '/updateinfo.json'
        replace: '$http_x_ingress_path/updateinfo.json'
      - mode: body
        match: '/jsonrpc.js'
        replace: '$http_x_ingress_path/jsonrpc.js'
      - mode: body
        match: '"imageproxy/'
        replace: '"$http_x_ingress_path/imageproxy/'
      - mode: body
        match: '"/imageproxy/'
        replace: '"$http_x_ingress_path/imageproxy/'
      - mode: body
        match: 'startsWith\("/imageproxy"'
        replace: 'startsWith("$http_x_ingress_path/imageproxy"'
      - mode: body
        match: 'startsWith\("imageproxy"'
        replace: 'startsWith("$http_x_ingress_path/imageproxy"'
      - mode: body
        match: 'indexOf\("imageproxy"'
        replace: 'indexOf("$http_x_ingress_path/imageproxy"'
      - mode: body
        match: '="music/'
        replace: '="$http_x_ingress_path/music/'
      - mode: body
        match: '"/music/'
        replace: '"$http_x_ingress_path/music/'
      - mode: body
        match: '"html/'
        replace: '"$http_x_ingress_path/html/'
        #replace: '"$http_x_ingress_path/material/html/'
      - mode: body
        match: '"/html/'
        replace: '"$http_x_ingress_path/html/'
        #replace: '"$http_x_ingress_path/material/html/'
      - mode: body
        match: 'resolveImageUrl\("/'
        replace: 'resolveImageUrl("$http_x_ingress_path/'
      - mode: body
        match: 'return a.startsWith("/")?a:"/"+a'
        replace: 'return a.startsWith("/")?a:"$http_x_ingress_path/"+a'
      - mode: body
        match: 'url\(/'
        replace: 'url($http_x_ingress_path/'
        #replace: 'url($http_x_ingress_path/material/'
      - mode: body
        match: "window.location.href = '/'"
        replace: "window.location.href = '$http_x_ingress_path/'"
        #replace: "window.location.href = '$http_x_ingress_path/material/'"
      - mode: body
        match: 'url\(html'
        replace: 'url($http_x_ingress_path/html'
        #replace: 'url($http_x_ingress_path/material/html'
      - mode: body
        match: 'r.src=t.src,'
        replace: 'r.src=t.src.startsWith("/")?t.src:"$http_x_ingress_path/"+t.src,'
      - mode: body
        match: '"/material/'
        replace: '"$http_x_ingress_path/material/'
```
