### DISCUSSION TITLE
Using This To Dynamically Switch Between Local and Remote URLs?

### DISCUSSION THREAD

**Discussion by iamronr** [lovelylain/hass_ingress#42] [General]
Hello,

Is it possible to use this to switch between local URL (192.168.x.x:port) and remote url (example.example.com)?

Here's what's currently in my configuration.yml

```
ingress:
  jellyseerr:
    work_mode: iframe
    ui_mode: normal
    title: Request
    icon: mdi:movie-search
    url: 
      match: http://192.168.xx.xx:5055
      replace: http://192.168.xx.xx:5055
      default: https://request.xx.xx
```

**Comment by lovelylain** [comment]
Yes you can, this feature is designed for this purpose.
For example, you use http://hass.web.local/ to access HA from the internal network, and https://hass.example.com/ from the external, you want to use http://openwrt.web.local/ to access openwrt from the internal, and https://openwrt.example.com/ from the external. You can set match: (\w+://)hass(\..+), replace: $1openwrt$2, default: https://openwrt.example.com to achieve your goal.

**Reply by iamronr** [reply]
Any insight on what that would look like? Not quite sure how to go about it. Referring to my code above, what should I change because I’m not sure I’m using match and/or replace right…

I've updated my code. This is what I have so far, but it's still not routing properly when connected locally, only remotely:

```
ingress:
  jellyseerr:
    work_mode: iframe
    ui_mode: normal
    title: Request
    icon: mdi:movie-search
    url:
      match: (\w+://)192\.168\.##\.##:5055
      replace: $1request.xx.com
      default: https://request.xx.com
```

**Reply by lovelylain** [reply]
you should provide 4 urls:
1. local ha
2. remote ha
3. local jellyseerr
4. remote jellyseerr
match is used on ha url to judge if local or remote, if match use replace else use default.

**Reply by iamronr** [reply]
So it'll be like this? Not sure if I’m overthinking this… not sure where I should put ha’s remote url?

```
ingress:
  request:
    work_mode: iframe
    ui_mode: normal
    title: Request
    icon: mdi:movie-search
    url:
      match: http://192.168.#.#:8123 <— ha local
      replace: http://192.168.#.#:5055 <— jellyseerr local
      default: https://request.xx.com < — jellyseerr remote
```
