### DISCUSSION TITLE
Example: Eaton xComfort Smart Home Controller (SHC)

### DISCUSSION THREAD

**Discussion by Wuerger** [lovelylain/hass_ingress#46] [Show and tell]
https://www.eaton.com/de/en-gb/catalog/residential/xcomfort-smart-home-controller.html

NOTE: There is one issue when you hit the 'Logout' link in the SHC UI. This will redirect the ingress frame to the HA root page. I have not found the code to modify this behavior. Suggestions welcome :-)

```yaml
ingress:
  eaton:
    ui_mode: toolbar
    title: Eaton SHC
    icon: mdi:home
    url: <internal URL of SHC>
    rewrite:
      # rewrite body
      - mode: body
        match: "(href|src|rel|rpcURI|appRoot|pluginRoot|action)(\\s?=\\s?)('|\")\/"
        replace: "\\1\\2\\3$http_x_ingress_path/"
      - mode: body
        match: "(open|get)\\('\/"
        replace: "\\1('$http_x_ingress_path/"
      # rewrite headers
      - mode: header
        name: 'Location'
        match: '^\/'
        replace: '$http_x_ingress_path/'
      - mode: header
        name: 'Set-Cookie'
        match: '=/'
        replace: '=$http_x_ingress_path/'
```
