### DISCUSSION TITLE
Example how to use the hassio mode exactly

### DISCUSSION THREAD

**Discussion by Thyraz** [lovelylain/hass_ingress#51] [General]
Hi,

based on the docs I thought I get the idea how to use it, but I get a _"Unable to fetch add-on info of 'd5369777-music-assistant-beta'"_ error when I open the item from the sidebar.

My hope was, to get Music Assistant working in a webpage card or iframe later, so I can always access it regardless of my current connection (HTTP locally or HTTPS through Nabu Casa cloud remotely).

This is what my config looks like:

````
ingress:
  music_assistant:
    work_mode: hassio
    ui_mode: normal
    title: Music Assistant
    icon: mdi:music-box
    url: d5369777-music-assistant-beta
````

Any advice what I have to change to get it working?

Thanks in advance. :)

**Comment by Thyraz** [comment]
Ok, it started working with this config:

````
ingress:
  music_assistant_no_header:
    work_mode: hassio
    title: Music Assistant (without header for ingress dashboard integration)
    icon: mdi:music-box
    url: d5369777_music_assistant_beta
````

And it looks good when I click it on the sidebar: I get just the Music Assistant UI without a header or sidebar.
But when I embed it as iFrame in a dashboard, I get the sidebar visible inside the iFrame.
So I have to sidebars nested.

Is there any way to prevent this?

**Comment by Thyraz** [comment]
And another try, this time with Music Assistant as local URL instead of the hassio work_mode:

````
ingress:
  music_assistant_no_header:
    work_mode: ingress
    ui_mode: normal
    url: http://localhost:8095
    title: Music Assistant (no header)
    icon: mdi:music
````

and in the iFrame:
/api/ingress/music_assistant_no_header/

Works fine locally, but through the cloud it shows the login screen of HA with an endless loading indicator. :-/
