### DISCUSSION TITLE
Advice to integrate (external) Grafana instance?

### DISCUSSION THREAD

**Discussion by eigenphase** [lovelylain/hass_ingress#60] [Q&A]
(Trying to get help on the question I posted a while ago in the forum: https://community.home-assistant.io/t/hass-ingress-add-additional-ingress-panels-to-your-home-assistant-frontend/698518/9)

I have “TeslaMate” running on [teslamate.example.com](http://teslamate.example.com/) which I’d like to integrate in my HA dashboards. It’s not accessible from the outside and protected via HTTP basic auth.

There is a main dashboard under “/” and “/settings” and “/geo-fences” but the main part of TeslaMate is actually a Grafana instance that are all under “/dashboards”, e.g., “/dashboards/d/riqUfXfRs”.

Ideally I’d like to both/the whole thing but the more important part is Grafana. When I do not do any rewrite, I get the Grafana error message that things are not properly configured.

This is the closest I got to exposing this Grafana instance:

```
ingress:
  teslamate:
    title: TeslaMate
    work_mode: ingress
    url: https://user:pass@teslamate.example.com
    index: /dashboards/?orgId=1
    headers:
      host: teslamate.example.com
    ui_mode: toolbar
    rewrite:
      - mode: body
        match: "(href|src|rel|rpcURI|appRoot|pluginRoot|action)(\\s?=\\s?)('|\")\/"
        replace: "\\1\\2\\3$http_x_ingress_path/"
```

Now, when I enter the dashboard I get “Page not found” message from Grafana, but I can then click “Home” and select a dashboard. But then I get other error messages and no actual data is shown:

![image](https://github.com/user-attachments/assets/ece860b9-5a5f-4d8c-b610-5798b4111a25)

Do you have any advice on how to pass a Grafana instance via hass_ingress?
