### DISCUSSION TITLE
Jellyseer configuration

### DISCUSSION THREAD

**Discussion by reef-actor** [lovelylain/hass_ingress#65] [Q&A] [answered]
I have a mostly working Jellyseer configuration. The only issue I have is the /login page is not rewritten and 404's.
Has anyone had any success? I'm not sure what else to try.

Configurator
```
ingress:
  jellyseer:
    title: Jellyseer
    icon: mdi:docker
    url: http://home:5055
    rewrite:
      - mode: body
        match: "(href)(\\s?=\\s?)('|\")\/"
        replace: "\\1\\2\\3$http_x_ingress_path/"
      - mode: body
        match: "\"(\/(_next|avatarproxy|logo_full.svg|api/v1|images))"
        replace: "\"$http_x_ingress_path\\1"
```

Request initiator chain
```
Request initiator chain
https://mydomain.com/api/ingress/fCK-KF8kKo4dQ45dIJkoYfWCZ8P3YIiDLn5iAekVtM_a/
https://mydomain.com/api/ingress/jellyseer/
https://mydomain.com/login
```

**Comment by reef-actor** [comment, marked as answer]
It seems to be working now after adding a Location header rewrite. Below is my full configuration for Jellyseer

```
ingress:
  jellyseer:
    title: Jellyseer
    icon: mdi:television-classic
    url: http://home:5055
    rewrite:
      - mode: header
        name: 'Location'
        match: '^\/'
        replace: '$http_x_ingress_path/'
      - mode: body
        match: "(href|src)(\\s?=\\s?)('|\")\/"
        replace: "\\1\\2\\3$http_x_ingress_path/"
      - mode: body
        match: "\"(\/(_next|avatarproxy|logo_full.svg|api/v1|images))"
        replace: "\"$http_x_ingress_path\\1"
```
