### ISSUE TITLE
Blank page and assets errors

### ISSUE THREAD

**Issue by lucagobbi** [lovelylain/hass_ingress#1]
First of all, thank you for sharing this integration! I was struggling with ingress configs and then your solution came out.

I installed the package via HACS and then i added in my configuration.yaml this:

```yaml
ingress: 
  custom_addon_ingress: 
    title: Custom Addon Ingress 
    icon: mdi:cat 
    url: http://localhost:1865/admin
```
I can see that it is pointing to the correct instance but i reach a blank page and in the console i get some errors related to static assets like this one:

`http://homeassistant.local:9000/admin/assets/Rubik-BoldItalic.ttf net::ERR_ABORTED 404 (Not Found)`

I checked my addon and it is loading assets from that path but it cannot do it using the ingress function in HA.

Am i missing something in the config? Any guidance would be greatly appreciated! Thank you in advance!

**Comment by airdrummingfool** [comment]
I ran into this same issue when first attempting to set up Z-Wave JS UI as `url: http://localhost:8091/#/control-panel`. Splitting it to `url: http://localhost:8091` and `index: /#/control-panel` worked for me.

It's in the docs (but not super obvious) that access is limited to paths that contain the full path in the `url` key.

> index: string (optional, default empty) The relative URL of index page. If the url is http://127.0.0.1:45180/ui, all access must be under the /ui path; if the url is http://127.0.0.1:45180/ and the index is /ui, all paths of http://127.0.0.1:45180/ can be accessed.

So I'd suggest trying this config:

```yaml
ingress: 
  custom_addon_ingress: 
    title: Custom Addon Ingress 
    icon: mdi:cat 
    url: http://localhost:1865
    index: /admin
```

and thanks to lovelylain for this integration, I've been wishing for it for years!

**Comment by lucagobbi** [comment]
Thank you for your answer. Actually, I've already tried that without success. Now I'm getting a 404 NOT FOUND. Maybe I've made mistake in the custom addon config.yaml file.
```YAML
# other addon configs
ingress: true
ingress_entry: /admin
ingress_stream: true
```
