### ISSUE TITLE
BlueIris integration - weird failures....

### ISSUE THREAD

**Issue by ChirpyTurnip** [lovelylain/hass_ingress#11]
Hi,

So I now have this running with BlueIris and it works *really* well...except on one client. There is initially worked and then things got weird. 

Firstly I switched to using javascript H264 player the eliminate the latency problems that I was experiencing with the other player options. But, having got this working I navigated again from the ingress page, but when I came back the Ingress frame said:

_The video stream was lost. Attempting to reconnect.
Protocol error the stream did not start with "blue".
The videostream was lost. Due to rapid failures, automatic reconnection will resume at [time]._

And yet it worked perfectly when first connection was made?

But then it gets weirder.....when I changed the codec back to webcodecs or html5 the error persisted. Similarly, reloading the browser tab or dropping off and coming back to the HA side bar item, or restarting the browser, or completely clearing the cache, also fails...once the connection is lost it is all over.....

Now curiously I **could** select **another** group of cameras and they will connect....but returning the first group it fails _again_....which makes this problem even weirder as it is all the same configuration and the same BI instance....and the fact that some views include all the cameras from the broken view that now refuses to load also shows it's not the cameras themselves....

It's just.....weird. Broken but working. Working but broken.

But then things get harder. While this is now working fine on multiple PCs....the one that had the connectivity problemsis now not working *at all*....it just says "Authorisation Required" now and refuses to load anything....but it also will not prompt for credentials. 

Yet on the same browser on a different PC connecting to the same HA instance it work fine.....  :-(

Any ideas as to what is going on? Or how to hard code the required credentials into the configuration?

Thanks!

**Comment by lovelylain** [comment]
maybe cookie or localstorage problem, compare cookies and try delete cookie one by one to check.

**Comment by ChirpyTurnip** [comment]
I played around some more with this after work today and figure out how to do the auth for the configuration. For those who have the same problem, this is what I did:

1. In the web browser developer mode (F12) paste the following into the console: _encodedData = "Basic " + window.btoa('USERNAME:PASSWORD')_ 
2. Replace USERNAME and PASSWORD with your BlueIris credentials - make sure the ':' between these two is retained. 
3. Press Enter then copy the resulting string. As an example the test string above returns _'Basic VVNFUk5BTUU6UEFTU1dPUkQ='_
4. Edit secrets.yaml and add a snippet for BlueIris (the output without the quote marks) -->  _bi_auth: Basic VVNFUk5BTUU6UEFTU1dPUkQ=_

Now make your ingress config look like this:
```
#INGRESS
ingress:
  blue_iris:
    title: Blue Iris
    icon: mdi:cctv
    url: http://192.168.x.x:81
    expire_time: 3600
    ui_mode: normal
    index: /ui3.htm?t=live&group=ApproachZone3
    headers:
      authorization: !secret bi_auth
```
Restart Ingress using Developer Tools > YAML > INGRESS 

And then all of sudden, now that we force the authentication, there is no more username/password prompt, and the PC that refused to prompt and only gives the _Authorisation Required_ error works again!

So fixed, but not without forcing auth...but worth it as it is all less effort now! :-)

**Comment by TinyShark** [comment]
I found out that you can also pass a Remote-User header to Blue Iris with just a username:

```
ingress:
  blue_iris:
    title: Blue Iris
    icon: mdi:camera
    url: http://192.168.X.X:81
    ui_mode: toolbar
    index: /ui3.htm
    headers:
      Remote-User: <YOUR BI USERNAME>
```
