### ISSUE TITLE
Adding grafana

### ISSUE THREAD

**Issue by dandek01** [lovelylain/hass_ingress#13]
Hi,
This probably is not an issues with this integration, but I'm having trouble adding grafana. I just want to make some grafana dashboards and display it over nabu casa cloud that I'm using for ha remote access.
Most of things I tried works out of the box but I cant set up grafana, so I need your help.
I run nginx on my server and adguard on my openwrt router. I have a domain and I use adguard to do dns rewrite for my domain and subdomains back to my ha ip.
And this is working fine, got my ssl certs for domain and all subdomains. But for some reason I can't set up grafana.
Ie my config for frigate
```
ingress:
  frigate:
    title: Frigate
    icon: mdi:cctv
    url: 192.168.8.40:5000
    require_admin: true
```
And this is working out of the box. The question is how to set up grafana? 
Grafana is running on port 3100 and I have no problems accessing it over grafana.mydomain.com or 192.168.8.40:3100.

**Comment by lovelylain** [comment]
Grafana requires additional configuration to support ingress.
https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#root_url
I don’t know the specific configuration, maybe only the `root_url`.

Because you have no problems accessing it over grafana.mydomain.com, you can try using `work_mode: auth` to safely expose it to the external network.

**Comment by lovelylain** [comment]
A few days ago I integrated grafana, prometheus and cadvisor into HA sidebar, for grafana you can configure it as follows.

configuration.yaml:
```yaml
ingress:
  grafana:
    work_mode: ingress
    title: Grafana
    icon: mdi:chart-timeline
    url: grafana:3000
    headers:
      X-WEBAUTH-USER: admin
```
docker-compose.yml:
```yaml
services:
  grafana:
    image: grafana/grafana
    volumes:
    - xx/grafana.ini:/etc/grafana/grafana.ini
```
grafana.ini:
```
[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/api/ingress/grafana/
[security]
allow_embedding = true
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true
```
