### ISSUE TITLE
How to support Ubiquiti routers (UDM)

### ISSUE THREAD

**Issue by deiger** [lovelylain/hass_ingress#16]
The login page, `https://192.168.0.1/`, is redirected to `https://192.168.0.1/login?redirect=%2F`.

I tried:
```yaml
ingress:
  unifi:
    work_mode: ingress
    title: UniFi
    icon: mdi:router-network
    url: https://192.168.0.1/
```

But I'm getting a 502 error.
iframe and auth didn't work either.
