### ISSUE TITLE
Panel Item URL is not formed correctly, and headers don't seem to be sent

### ISSUE THREAD

**Issue by zerocool2k** [lovelylain/hass_ingress#2]
I set up my HASS Configurator behind nginx from Swag, with basic http authentication. Everything is docker containers.
Below is my ingress configuration:

```yaml
ingress:
  configurator:
    title: HASS Configurator
    ingress: true
    toolbar: true
    icon: wrench
    url: https://subdomain2.mydomain.com
    headers:
      authorization: "Basic [base64 encoded username:password]"
```

When I click on the "HASS Configurator" menu on the side menu, it just show the default swag page ("Welcome to your [SWAG](https://github.com/linuxserver/docker-swag) instance...")

I checked browser console and found that the "Request URL" was "https://subdomain1.mydomain.com [which is my home assistant URL]" & "/api/ingress/" & "/configurator/" , instead of "https://subdomain2.mydomain.com" which it is supposed to be.

Also, I don't see the authorization headers being sent in the request headers at all. Is the configuration above correct if I want to send authorization headers for basic http auth?
