### ISSUE TITLE
Cant get HTTPS to work with work_mode: ingress

### ISSUE THREAD

**Issue by Supermillhouse** [lovelylain/hass_ingress#20]
I cant get HTTPS to work with work_mode: ingress

I have been trying to get a https connection to the new Frigate update from a few days ago. (by frigate runs on a different machine to HA)

I have the below settings working fine but if I change the url to "url: https://192.168.X.X:8971" i get a "502: Bad Gateway" in the window, any ideas?

ingress:
  frigate_ingress:
    work_mode: ingress
    require_admin: true
    ui_mode: toolbar
    title: Frigate
    icon: mdi:webcam
    url: http://192.168.X.X:5000

**Comment by chrisbennight** [comment]
same issue here I believe;  I have a music assistant instance running behind traefik at https://ma.domain.tld.  In my case it's all running in docker on the same instance and if I change my url to point to http://server.domain.tld:8095 it works (same ip that traefik is proxying to)

works
```
ingress:
  music_assistant:
      title: Music Assistant
      work_mode: ingress
      icon: mdi:speaker
      ui_mode: normal
      url: http://server.domain.tld:8095
```

fails
```
ingress:
  music_assistant:
      title: Music Assistant
      work_mode: ingress
      icon: mdi:speaker
      ui_mode: normal
      url: https://ma.domain.tld
```

http://server.domain.tld:8095/ and https://ma.domain.tld/ both resolve properly in a browser and via wget inside the home assistant container

**Comment by lovelylain** [comment]
try add host header:
```
ingress:
  music_assistant:
    title: Music Assistant
    icon: mdi:speaker
    url: https://ma.domain.tld
    headers:
       host: ma.domain.tld
```
