### ISSUE TITLE
Hide panel from sidebar

### ISSUE THREAD

**Issue by jmccrohan** [lovelylain/hass_ingress#21]
Hi @lovelylain,

Thanks for creating this integration. It is just what I was looking for, although my usecase is probably a little obscure. Similar to #10, I'm looking for a way to hide the panel entry in the sidebar. i have tested the `parent` config option, but it doesn't do what I need (or perhaps I'm misunderstanding what it does).

First a bit of context; I use a combination of split horizon DNS and Cloudflared mTLS certs to use a single DNS name (`homeassistant.my-tld.com`) to access my HASS instance internally and externally. Internally, I use [nginx_proxy](https://github.com/home-assistant/addons/tree/master/nginx_proxy) + letsencrypt to serve HASS over HTTPS to LAN clients. My router has a static `homeassistant.my-tld.com` DNS entry pointing to my local HASS server. Externally, I use Cloudflared to serve my `homeassistant.my-tld.com` instance to selected devices secured with mTLS certs. All works great.

I have an insecure HTTP only device which I would like to expose within HA as an `iframe` card. I want to use `hass_ingress` to proxy my requests to allow me to wrap them in TLS both internally and externally. I don't want it exposed as a sidebar panel.

Using the following config, all is working except for the extra sidebar panel.  
```
ingress: 
  child: 
    title: Example 
    work_mode: ingress 
    ui_mode: toolbar 
    icon: mdi:person 
    url: http://192.168.12.134:8080
```

Adding `parent: parent ` gives me the following error:
`2024-08-19 22:43:10.803 ERROR (MainThread) [custom_components.ingress] parent panel[parent] not found, skip child panel[child]!`

Is this possible?

**Comment by lovelylain** [comment]
The parent option make the panel as other panel's child, you can visit the child panel with the parent panel's url. For example:
```
ingress:
  parent:
    work_mode: iframe
    ui_mode: replace
    title: Automation
    icon: mdi:link 
    url: /config/automation/dashboard
  child: 
    parent: parent
    title: Example 
    work_mode: ingress 
    ui_mode: toolbar 
    icon: mdi:person 
    url: http://192.168.12.134:8080
```
You can use `/parent` visit the parent panel, `/parent/child` visit the child panel. The child panel is ingress work mode, you can also use `/api/ingress/child` visit it.
