### ISSUE TITLE
Zigbee2Mqtt with token

### ISSUE THREAD

**Issue by ThomasCr** [lovelylain/hass_ingress#35]
Can u please add an example, on how to add the auth token to the url:

https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/411
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/commit/9feeab620bc5e99152423a3a0c91c9172fc32b37#diff-b64416271dd0ef426fd84e150e12fb02ae878a126497e3ea95e692971f4b2283R55

**Comment by lovelylain** [comment]
Not support, please don't set token, or add it with nginx.

Browser -> HA Ingress -> Nginx -> Zigbee2Mqtt
configuration.yaml:
```
ingress:
  zigbee2mqtt:
    title: Zigbee2MQTT
    icon: mdi:zigbee
    url: 127.0.0.1:80
    headers:
      host: zigbee2mqtt
```

nginx.conf:
```
server {
  listen 127.0.0.1:80;
  server_name zigbee2mqtt;
  location / {
    set $upstream zigbee2mqtt:8080;
    set $args $args&token=xxxx;
    proxy_set_header Host $http_x_forwarded_host;
    proxy_pass http://$upstream;
  }
}
```
