### ISSUE TITLE
Not working on android app?

### ISSUE THREAD

**Issue by karl0ss** [lovelylain/hass_ingress#37]
More a question I guess, but I have this installed and working fine with the following config 

```
ingress:
  mealie:
    work_mode: iframe
    title: Mealie
    icon: mdi:food
    url: http://192.168.4.10:9925
```

On my desktop pc using chrome I can see my mealie instance when clicking the icon, but on my screen in the kitchen (android tablet running the Home Assistant (beta) apk, clicking on the icon just shows a white page and doesn't appear to load?

Is this to be expected?

Thanks

**Comment by lovelylain** [comment]
iframes will have cors problems, and different browsers may behave inconsistently. Please try the ingress working mode.

**Comment by karl0ss** [comment]
WIth `work_mode: ingress`

I just get 

![image](https://github.com/user-attachments/assets/d8a3d90c-405c-4b63-ac45-96230033d255)


on both my Chrome browser and the Adnroid APK

**Comment by edekeijzer** [comment]
Any update on this (or how to troubleshoot)? I have the same white screen with spinner with Mealie in ingress mode.

**Comment by karl0ss** [comment]
I never got it working on anyhting other than iframe so just setteled with that...

**Comment by edekeijzer** [comment]
I just found out that it's trying to access .js files like ```/_nuxt/6762d48.js``` which obviously aren´t accessible. If I manually change the path to ```/api/ingress/mealie/_nuxt/6762d48.js``` I get a minimized JS file.
I have tried rewriting but not sure if I'm doing it correctly as it does not appear to work :
```yaml
  mealie:
    ui_mode: toolbar
    title: Mealie
    icon: mdi:silverware-variant
    url: http://mealie.internal:9000
    rewrite:
    - mode: body
      match: '/(_nuxt\/.+\.js)'
      replace: '$http_x_ingres_path/\1'
```

I've attached [mealie.html](https://github.com/user-attachments/files/19742149/mealie.txt)
