### ISSUE TITLE
Ingress with Authentication no longer works from external network in HA 2024.10.4

### ISSUE THREAD

**Issue by zerocool2k** [lovelylain/hass_ingress#39]
```
ingress:
  portainer:
    work_mode: ingress
    ui_mode: toolbar
    title: Portainer
    url: http://192.168.x.x:9000
    index: /#!/2/docker/containers
```
The above ingress configuration has worked for me for the last year. However, I have just updated to HA 2024.10.4 and now I can no longer log in to Portainer (by entering credentials manually on the Portainer login screen) from an external network. It says "unable to log in" and halt the whole server with this:
<img width="460" alt="image" src="https://github.com/user-attachments/assets/1ef8da55-5c89-47cd-aad8-d2e40ac2d026">

Did anything change in the new HA version?
