### ISSUE TITLE
Getting Blue Iris NVR working

### ISSUE THREAD

**Issue by mutasim** [lovelylain/hass_ingress#4]
(Great library btw - this has really been a missing piece of the puzzle for me)

Opening this issue to working through setting up Blue Iris NVR. I haven't got it fully working yet but here's my progress so far..

Config:
```
blue_iris:
  title: Blue Iris
  icon: mdi:camera
  url: http://<ip address of blue iris pc>:<blue iris port>
  ui_mode: toolbar
  index: /ui3.htm
``` 

The UI loads, the cameras load intermittently and I'm getting the following error:

`JSON API unreachable at "/json?_login". This is may be the result of using a reverse-proxy server incorrectly. ` 

Perhaps I need to look at this sub_filter stuff?
