### ISSUE TITLE
NODE-RED Token login

### ISSUE THREAD

**Issue by zelo66** [lovelylain/hass_ingress#40]
I have been trying to add a token login to NODE-RED for a few days now.

According to the example provided, this is possible.

```
 nodered:
    require_admin: true
    title: Node-RED
    icon: mdi:sitemap
    url: http://127.0.0.1:45180
    headers:
      authorization: !secret nodered_auth
```

I generated a new Bearer token and substituted it as the header. Unfortunately the NR login window is still displayed.

I generated the token according to these instructions:
https://nodered.org/docs/user-guide/runtime/securing-node-red#editor--admin-api-security

My code:

```
  nodered:
    work_mode: ingress
    require_admin: true
    title: Node-RED
    icon: mdi:sitemap
    url: "http://10.0.0.83:1880/"
    headers:
       authorization: "Bearer sdadasdasdaTOKENdsadasd"
#       host: nodered.lan.zelo.ovh
#    url: https://nodered.lan.zelo.ovh
```

Can you tell what I am doing wrong?
