### ISSUE TITLE
TeslaMate webpage render issue

### ISSUE THREAD

**Issue by wyx087** [lovelylain/hass_ingress#41]
Thanks for this great integration. 

I'm trying to use this integration to show TeslaMate running in Docker on a different VM, but the webpage doesn't appear to render properly. 

This is in my configuration.yaml: 
```
ingress:
  teslamate:
    title: TeslaMate
    icon: mdi:car-connected
    url: http://192.168.5.13:4000/
```

This is what it looks like via HASS Ingress: 
![image](https://github.com/user-attachments/assets/95345bfc-b9c7-4aa4-9ae1-7c553bf63c53)

This is what it supposed to look like: 
![image](https://github.com/user-attachments/assets/ae1002bf-be3e-4ca8-afdd-693c0c0e951c)

In TeslaMate HA add-on, there is a bit of code that may give us hint on how ingress support was achieved: 
https://github.com/lildude/ha-addon-teslamate/blob/main/rootfs/etc/s6-overlay/s6-rc.d/teslamate/run
```
ingress_entry=$(curl -X GET \
                     -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" \
                     -H "Content-Type: application/json" \
                     -s http://supervisor/addons/self/info | \
                     jq -r '.data.ingress_entry')

export URL_PATH=$ingress_entry
```
And this is TeslaMate documentation talking about this URL_PATH: 
https://docs.teslamate.org/docs/configuration/environment_variables/

Unfortunately I'm at a complete loss for this kind of stuff. Can anyone provide some pointers as to what need to be added and where, to make TeslaMate play nicely with HASS ingress? 

Thanks very much :)

**Comment by lovelylain** [comment]
Add rewrite configuration refer to these links:
https://github.com/lildude/ha-addon-teslamate/blob/main/rootfs/etc/nginx/conf.d/teslamate.conf#L30
https://github.com/lovelylain/hass_ingress/blob/main/addons-for-docker-installation.md#openwrt

**Comment by wyx087** [comment]
I had some attempt to no success, my Regex knowledge is extremely basic..... 

It either says `500 Internal Server Error Server got itself in trouble`, or blank page, or same broken screen. 

```
  teslamate:
    title: TeslaMate
    icon: mdi:car-connected
    url: http://192.168.5.13:4000/
    rewrite:
      - mode: body
        match: /(href=\"\\/\")/
        replace: href=\"$http_x_ingress_path\/\"
      - mode: body
        match: /(url\\(\\/)/
        replace: url\\($http_x_ingress_path\/
      - mode: body
        match: /(\"\\/live\")/
        replace: \"$http_x_ingress_path\/live\"
      - mode: body
        match: /(\"\\/js\\/\")/
        replace: \"$http_x_ingress_path\/js\/\"
```

A little help would be much appreciated? 

Just to confirm, there is only these 4 need re-writing, correct? 

```
        # Home URLs in the HTML
        sub_filter 'href="/"' 'href="$http_x_ingress_path/"';
        
        # Fonts in the CSS
        sub_filter 'url(/' 'url($http_x_ingress_path/';

        # Update fixed paths in the .js files
        sub_filter '"/live"' '"$http_x_ingress_path/live"';
        sub_filter '"/js/"' '"$http_x_ingress_path/js/"';
```

Thanks so much
