### ISSUE TITLE
[ENH] Allow multiple instances of tab

### ISSUE THREAD

**Issue by scetu** [lovelylain/hass_ingress#43]
Hello, really neat new feature with tab support.

Would it be possible to create multiple instances of tab entry, with different child objects?
Currently only one instance of `tabs` is supported, and it needs to be named `tabs`.

```
ingress:
  tabs:
    work_mode: custom # MUST
    url: /files/ingress/ha-tabs-ingress.js # MUST
    title: HA Companions
    icon: mdi:home-assistant
  zigbee2mqtt:
    parent: tabs
    title: Zigbee2MQTT
    icon: mdi:zigbee
    url: 
  frigate:
    parent: tabs
    title: Frigate
    icon: mdi:cctv
    url: 
  emqx:
    parent: tabs
    title: EMQX
    icon: mdi:leak
    url: 

  hosting-media-management:
    work_mode: custom # MUST
    url: /files/ingress/ha-tabs-ingress.js # MUST
    title: Homelab Hosting
    icon: mdi:server-network
    require_admin: true
  radarr:
    parent: hosting-media-management
    title: Radarr
    icon: mdi:movie-search
    url: 
    index: /radarr/
    headers:
      authorization: !secret raddar
  sonarr:
    parent: hosting-media-management
    title: Sonarr
    icon: mdi:movie-search
    url: 
    index: /sonarr/
    headers:
      authorization: !secret sonarr
```

Thank you for your work!
