### ISSUE TITLE
Custom Brand Icons Not Working

### ISSUE THREAD

**Issue by iamronr** [lovelylain/hass_ingress#47]
I'm trying to use custom brand icons (https://github.com/elax46/custom-brand-icons) in Ingress. They'll show up when I first configure them, but after a brief period, they'll disappear. The regular `mdi:icons` work fine, but `phu:icons` aren't staying populated. I'm running the latest Home Assistant Core (2024.12.5) and the latest version of ingress. I currently don't have any logs to produce. I can try to provide that tomorrow.

`Side Bar`
![TRC 3](https://github.com/user-attachments/assets/486866ff-2bfc-4f81-9848-798ac0714cfb)

`yaml in configuration.yaml`
```
sabnzbd:
    work_mode: iframe
    ui_mode: normal
    title: SABnzbd
    icon: phu:sabnzbd
    url: 
      match: https://ha.####.dev
      replace: https://sab.####.dev
      default: http://192.168.###.##:8085

uptime:
    work_mode: iframe
    ui_mode: normal
    title: Uptime
    icon: phu:kuma
    url: 
      match: https://ha.####.dev
      replace: https://uptime.####.dev
      default: http://192.168.###.##:3001
```
