### ISSUE TITLE
Help needed: Tandoor Access in Homeassistant

### ISSUE THREAD

**Issue by Gridomin** [lovelylain/hass_ingress#49]
Hi everyone,
I could really need some help getting Ingress to work with Tandoor in HomeAssistant.
I found the posts here (https://community.home-assistant.io/t/ingress-access-for-tandoor-recipes/717859), but i dont get it working for days/weeks.

I am accessing HomeAssistant from an external Domain (and reverse proxy called) ha.example.com (Placeholder), leading to the internal up 192.168.178.103:8123.

Steps I did:
I've installed Tandoor Add-On in HomeAssistant and put in the "allowed-hosts" in the add-on configuration (external domain and internal IPs of HA).
In file editor I edited to config.yaml of Tandoor to look like this:

```
TZ: Europe/Paris
REMOTE_USER_AUTH: 1
SCRIPT_NAME: /api/ingress/tandoor_recipes
JS_REVERSE_SCRIPT_PREFIX: /api/ingress/tandoor_recipes
STATIC_URL: /api/ingress/tandoor_recipes_static/static/
MEDIA_URL: /api/ingress/tandoor_recipes_static/media/
```

I've installed Ingress via HACS.
Then added this into the configuration.yaml of HomeAssistant:
```
ingress:
  tandoor_recipes:
    title: Tandoor Recipes
    icon: mdi:silverware-fork-knife
    url: tandoor_recipes:8080$http_x_ingress_path
    headers:
      Remote-User: admin
      X-Script-Name: $http_x_ingress_path
      Origin: $auto
  tandoor_recipes_static:
    parent: tandoor_recipes
    work_mode: subapp
    url: tandoor_recipes:8080/api/ingress/tandoor_recipes$http_x_ingress_path
```

Result:
Tandoor Recipes is shown in the sidebar, but clicking on it is showing "502: Bad Gateway".
If I try to open the UI from the Add-On-Menu, a tab is opening, tryping to access ha.example.com:9928, which is not valid and so not working either.
Trying to manually access the internal ip of Tandor (192.168.178.103:9928 oder homeassistant.local:9928) doesn't work becauce of "internal server error".

The protocol of Tandoor is showing me in constant repeats this error:

> [2025-01-06 10:26:33 +0100] [360] [ERROR] Error handling request /openapi
> Traceback (most recent call last):
>   File "/opt/recipes/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 282, in handle
>     keepalive = self.handle_request(req, conn)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/recipes/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 319, in handle_request
>     resp, environ = wsgi.create(req, conn.sock, conn.client,
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/recipes/venv/lib/python3.12/site-packages/gunicorn/http/wsgi.py", line 188, in create
>     raise ConfigurationProblem(
> gunicorn.http.errors.ConfigurationProblem: Configuration problem: Request path '/openapi' does not start with SCRIPT_NAME '/api/ingress/tandoor_recipes'
> ::ffff:127.0.0.1 - - [06/Jan/2025:10:26:33 +0100] "GET /openapi HTTP/1.1" 500 0 "-" "-"

Could anyone please give me some advise, what to do?
Thank you very much!!
Dominik
