### ISSUE TITLE
Passing url parameters

### ISSUE THREAD

**Issue by mutasim** [lovelylain/hass_ingress#5]
My config:
```
blue_iris:
  title: Blue Iris
  icon: mdi:camera
  url: http://10.0.10.12
  ui_mode: toolbar
  index: /ui3.htm
``` 

This works and allows me to access the above resource at [hass URL]/blue_iris

Is it possible to pass a url parameter through? Sometimes I want to be able to link directly to http://10.0.10.12/ui3.htm?tab=clips or http://10.0.10.12/ui3.htm?tab=alerts&alert_id=123436456.

I tried [hass URL]/blue_iris?tab=clips but it didn't pass through the url params.

My use case is being able to deeplink to CCTV camera clips from Hass notifications. If this isn't possible yet, could I please make this a feature request?

**Comment by lovelylain** [comment]
If you solve the issue with absolute links, it should work.

**Comment by lovelylain** [comment]
#4

**Comment by lovelylain** [comment]
If you solve the issue with absolute links, it should work. #4

**Comment by lovelylain** [comment]
If you solve the issue with absolute links, it should work. #4

**Comment by lovelylain** [comment]
I understand what you mean now. I want to know the usage scenario here. Add an index parameter to overwrite the one configured in the configuration file. You need to URL encode this parameter. Can it meet your needs? For example, use `[hass URL]/blue_iris?index=ui3.htm%3Ftab%3Dclips` to access `http://10.0.10.12/ui3.htm?tab=clips`

**Comment by mutasim** [comment]
I think your proposal is great because others might have different paths they want to deeplink to rather than just URL params. Sounds like your approach gives maximum flexibility to deeplink into other pages within the app or add URL params to the same index page. 👍

**Comment by lovelylain** [comment]
supported in 1.0.3

**Comment by mutasim** [comment]
Wow that was quick! I'll test and report back.

**Comment by mutasim** [comment]
Tested with url params and with a different path altogether.. works great!! thanks

**Comment by mutasim** [comment]
I have it setup so all of my HA users are effectively the same BI user. So there's no per user auth/profiles.

**Comment by mutasim** [comment]
You might be able to pass BI auth credentials via URL params and use templates to do different values for each HA user (?)

**Comment by lovelylain** [comment]
@TinyShark if your service use basic auth, you can add authorization header to bypass the authentication in ingress work_mode.

**Comment by TinyShark** [comment]
Cool! seems to be working with the below:

```
ingress:
  blue_iris:
    title: Blue Iris
    icon: mdi:camera
    url: http://IP:PORT
    ui_mode: normal
    #work_mode: auth
    index: /ui3.htm
    headers:
      Remote-User: 'your-user'
```

Last piece of the puzzle would be how to pull the current home assistant user and pass that as the `Remote-User` presumably I can't use a template like i would do in the front end?

**Comment by mutasim** [comment]
@TinyShark have you been able to work out how to save images/clips from BI when using the HA iOS app? 

Also would be good to hear what your use case is for different BI users.

**Comment by TinyShark** [comment]
@mutasim I have not really looked into that yet as my main use case within HA is to simply view BI's UI3. I do have BI send images via MQTT to HA on certain triggers (e.g doorbell cam etc).

The reason I'd like to authenticate blue iris with different users is so that I can configure certain users/devices to specific camera groups and also different streaming schedules as defined in blue iris' user settings.

Looking at the docs for Ingress it seems that the header information could be available and for that to be passed on as a header through this component.

https://developers.home-assistant.io/docs/add-ons/security#authenticating-a-user-when-using-ingress

I'm wondering if in a similar fashion to:

`name = request.headers.get('X-Ingress-Name')`
 
you could have additional gets for the user id such as:

```
remote_user_id = request.headers.get('X-Remote-User-Id')
headers['Remote-User'] = remote_user_id
```

or user name etc:

```
remote_user_name = request.headers.get('X-Remote-User-Name')
headers['Remote-User'] = remote_user_name
```

and then in the config yaml we could put something like this:

```
ingress:
  panel:
    title: Blue Iris
    icon: mdi:icon
    url: http://X.X.X.X
    index: /ui3.htm
    forward_headers:
      Remote-User: true
```

**Comment by lovelylain** [comment]
@TinyShark Currently hass_ingress does not support passing user information. I already have an idea on how to pass user information, but it is a bit complicated and takes time to implement. Maybe you will be provided with a configuration item as shown below:
```
ingress:
  blue_iris:
    title: Blue Iris
    icon: mdi:icon
    url: http://X.X.X.X
    index: /ui3.htm
    user_headers:
      user_id_a:
        Remote-User: aaa
      user_id_b:
        Remote-User: bbb
```
