### ISSUE TITLE
Grafana "message not found" / stops working after some hours.

### ISSUE THREAD

**Issue by zimbo86** [lovelylain/hass_ingress#55]
Hi,

i´m struggeling to get grafana constantly work. 

I configured this:

configuration.yaml:
```
ingress:
  grafana:
    work_mode: ingress
    title: Grafana
    icon: mdi:chart-timeline
    url: grafana:3000
    headers:
      X-WEBAUTH-USER: admin
``` 

grafana.ini:
```
[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/api/ingress/grafana/
[security]
allow_embedding = true
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true
```

This initially works, however after some time i receive this error:

![Image](https://github.com/user-attachments/assets/b2195c22-3aea-402d-9726-37548c82474c)
