### ISSUE TITLE
Access sub url

### ISSUE THREAD

**Issue by lich2000117** [lovelylain/hass_ingress#57]
Hello, thank you for your work!!

I wonder what would be the best way to implement something like this? 

Accessing a sub page os sth, currently it gives me blank result.

Thank you!

```
ingress:
  frigate:
    ui_mode: toolbar
    title: frigate
    icon: mdi:cctv
    url: http://192.168.1.3:5000
  frigate_config:
    ui_mode: toolbar
    title: frigate Config
    icon: mdi:cctv
    url: http://192.168.1.3:5000/config
```

**Comment by lich2000117** [comment]
Sovled, 

```
  frigate_config:
    ui_mode: toolbar
    title: frigate Config
    icon: mdi:cctv
    **index: "/config/"**
    url: http://192.168.1.3:5000

```
