### ISSUE TITLE
How to add Alist webpage using this integration?

### ISSUE THREAD

**Issue by liyuxuan7762** [lovelylain/hass_ingress#59]
I install the alist add-on on my home assistant server. Now I want to opent the alist webpage using ingress feature. How I can config it?

```yaml
ingress:
  openwrt:
    title: iStoreOS
    icon: mdi:router-wireless-settings
    url: http://192.168.123.171/
    headers:
      # auto login for openwrt ingress
      http-auth-user: ***
      http-auth-pass: ****
    # "fix" absolute URLs by rewriting the response body
    rewrite:
      # for HTML response
      - mode: body
        match: /(luci-static|cgi-bin)/
        replace: $http_x_ingress_path/\1/
      # for JS init code
      - mode: body
        match: \\/(luci-static|cgi-bin|ubus)\\/
        replace: $http_x_ingress_path\/\1\/
      # for login response
      - mode: header
        name: "(Location|Set-Cookie)"
        match: /cgi-bin/
        replace: $http_x_ingress_path/cgi-bin/
  fileservice:
    title: Alist
    icon: mdi:router-wireless-settings
    url: http://192.168.123.174:5244/
```

Some screenshoots

![Image](https://github.com/user-attachments/assets/b239ff24-6bd2-45f6-b546-70a3d36101e4)

![Image](https://github.com/user-attachments/assets/403959d7-d0a8-492e-b57f-314bba5f7755)
