### ISSUE TITLE
Multiple (related? issues) Data not coming through from remote device UI / unable to log into another GUI / third one not loading at all

### ISSUE THREAD

**Issue by sparkydave1981** [lovelylain/hass_ingress#6]
I'm trying to log in to my local power meter but the UI of the device shows 'no configuration' as if the Ingress tab is unable to access it properly.

### First one

**Integration code**
```
ingress:
  iotawatt:   # loads but has no access to device data
    title: IoTaWatt
    icon: mdi:meter-electric
    require_admin: true
    ui_mode: toolbar
    url: http://192.168.30.16
```

**Ingress tab UI screenshot**

![image](https://github.com/lovelylain/hass_ingress/assets/7628509/1b2c843a-2597-4cd6-a6a9-db85a5a1e4f3)

**Example screenshot using the Firefox add-on (logged in from same HA browsing window)**

![image](https://github.com/lovelylain/hass_ingress/assets/7628509/4ca9a902-e6dc-4de8-b860-5b8bcff3817f)

### Second one

**Integration code**
```
ingress:
  nvr:   # loads but can't log in
    title: NVR
    icon: mdi:cctv
    require_admin: true
    ui_mode: toolbar
    url: http://192.168.0.100
```
**Ingress tab UI screenshot**

![image](https://github.com/lovelylain/hass_ingress/assets/7628509/aa3c6c7e-8302-48c8-b388-2496bf099fd7)

So with this one, I enter the username and password and then some popup appears (not something I get in a normal browser) but I can't see any text in the popup.  I'm unable to log in to the NVR's UI.

### Third potentially related issue...

**Integration code**
```
ingress:
  nas:   # not working
    title: NAS
    icon: cil:synology-nas
    require_admin: true
    ui_mode: toolbar
    url: http://192.168.0.15:5000
```

**Ingress tab UI screenshot**

![image](https://github.com/lovelylain/hass_ingress/assets/7628509/d00df79b-1f48-4b14-b11e-2a565d42725b)
![image](https://github.com/lovelylain/hass_ingress/assets/7628509/778933e2-0a44-4e15-8f25-a3387b8f77e0)

This one simply times out....

Sorry if I should have split these up into 3 issues but I have a feeling that they might all simply need some sort of additional config that I'm not savvy enough for.
