### ISSUE TITLE
Home Assistant 2025.5 breaks tabs

### ISSUE THREAD

**Issue by wyx087** [lovelylain/hass_ingress#62]
hass_ingress created tabs no longer respond to click on computer and tap on HA app (ios). The look of them also changed, icons seems to be bunched together. 

![Image](https://github.com/user-attachments/assets/b80e67f8-275d-4df1-9c9f-2ffec25e8a5b)

Normal HA dashboard using icons in 2025.5 seems to be more spread out: 

![Image](https://github.com/user-attachments/assets/7eb12595-a283-4829-bfc9-3a7cee7fadb4)

YAML unchanged from many updates before 2025.5. 

```
ingress:
  tesla_data_tabs:
    work_mode: custom # MUST
    url: /files/ingress/ha-tabs-ingress.js # MUST
    title: Tesla Data
    icon: mdi:car-info
  grafana:
    parent: tesla_data_tabs
    title: Grafana
    work_mode: ingress
    ui_mode: toolbar
    icon: mdi:database-eye-outline
    url: http://192.168.5.13:3000/
    headers:
      X-WEBAUTH-USER: admin
  powerwall:
    parent: tesla_data_tabs
    title: Powerwall
    work_mode: ingress
    ui_mode: toolbar
    icon: mdi:home-battery-outline
    url: http://192.168.5.13:9000/
    headers:
      X-WEBAUTH-USER: admin
  teslamate:
    parent: tesla_data_tabs
    title: TeslaMate
    ui_mode: toolbar
    icon: mdi:car-connected
    url: http://192.168.5.13:4000/
    rewrite:
      - mode: body
        match: \/live
        replace: "$http_x_ingress_path/live"
      - mode: body
        match: \/js\/
        replace: "$http_x_ingress_path/js/"
      - mode: body
        match: url\(\/
        replace: url($http_x_ingress_path/
      # For menu links
      - mode: body
        match: href="\/([^"]+)"
        replace: href="$http_x_ingress_path/\1"
      # For logo homepage link
      - mode: body
        match: href="\/"
        replace: href="$http_x_ingress_path/"
      - mode: body
        match: \/images
        replace: "$http_x_ingress_path/images"
      # Rewrite absolute paths for static assets in HTML responses (like <link> tags)
      - mode: body
        match: href="/(assets/[^"]+)"
        replace: href="$http_x_ingress_path/\1"
      # Rewrite JavaScript file paths in <script> tags
      - mode: body
        match: src="/(assets/[^"]+)"
        replace: src="$http_x_ingress_path/\1"
      # Rewrite absolute paths in JS/CSS files (like url("/assets/..."))
      - mode: body
        match: url\("/(assets/[^"]+)"
        replace: url("$http_x_ingress_path/\1")
      # MIME type correction (if needed for CSS/JS responses)
      - mode: header
        name: Content-Type
        match: text/plain
        replace: text/css
  wireless_tabs:

```
