### ISSUE TITLE
Issue with Zigbee2MQTT not displaying remotely

### ISSUE THREAD

**Issue by happyhammer7** [lovelylain/hass_ingress#64]
I have added the following to my config.yaml file 

`ingress:
  zigbee2mqtt:
    ui_mode: toolbar
    title: Zigbee2mqtt
    icon: mdi:zigbee
    url: http://192.168.1.51:9442
    index: /#/`

I can access the webpage when on my local network and it works as expected. However, as soon as I switch to a remote connection, the webpage is blank. I am using cloudflare tunnel for home assistant with my domain homeassistant.mydomain.com, which is fully accessible. 

I have read the guides but not sure if I am missing some configuration with it. Zigbee2mqtt is not using authorisation if that makes any difference.

**Comment by Swimmer71** [comment]
The format must look like this in configuration.yaml:

```
ingress:
  zigbee2mqtt:
    work_mode: hassio
    title: New Name
    icon: mdi:zigbee
    url: 1234abcd_zigbee2mqtt

```
use the relative URL path AND include the numbers and characters in front of the zigbee instance. Can be found on browsers address field when you open the zigbee page.
