### ISSUE TITLE
Configuration of vscode (code-server)

### ISSUE THREAD

**Issue by tbnobody** [lovelylain/hass_ingress#66]
I am running the latest (4.100.3) version of code-server (from https://github.com/coder/code-server) and configured ingress in the following way:
```yaml
ingress:
  vscode:
    #work_mode: ingress
    title: VSCode
    icon: mdi:microsoft-visual-studio-code
    url: http://127.0.0.1:8080
    require_admin: true
```

When accessing the entry via the sidebar, the server just responds:  `502 Bad Gateway`

Code server responds correctly when I try to access it using `curl -i "http:localhost:8080"`

Any hint is highly appreciated!
