### ISSUE TITLE
Very weird thing happens when using URL in an iframe...

### ISSUE THREAD

**Issue by eigenphase** [lovelylain/hass_ingress#68]
I am trying to use hass_igress to integrate CheckMK:

```
ingress:
  checkmk:
    title: CheckMK
    work_mode: ingress
    url: http://10.227.4.12:8080/
    index: /cmk/check_mk/login.py?_origtarget=/cmk/check_mk/dashboard.py?name=simple_problems&_username=homeassistant&_password=xxxxxxx&_login=1
    ui_mode: toolbar
    icon: mdi:monitor-dashboard
    rewrite:
      - mode: header
        name: "(Location|Set-Cookie)"
        match: /cmk/
        replace: $http_x_ingress_path/cmk/
```

Works like a charm when I open the side panel (or navigate to "/checkmk").

However, I would like to integrate exactly this page in an iFrame (to be used in a dashboard). If I use "/checkmk" as URL for the iframe it loads the main page, not the page referenced by "index". Hence re-using the full URL, including the "index" in the iframe:

```
type: iframe
url: >-
  /api/ingress/checkmk/cmk/check_mk/login.py?_origtarget=/cmk/check_mk/dashboard.py?name=simple_problems&_username=homeassistant&_password=xxxxxxx&_login=1
aspect_ratio: 50%
```

However, what I get then in the iframe is the Home Assistant load screen that spins forever at "loading data...":

<img width="578" alt="Image" src="https://github.com/user-attachments/assets/b34d6f38-a47b-4c79-a371-4bffdeb72dcf" />

To make things even more weird, it works if I **first** open the normal side panel and then go to the iframe. It continues to work for the session. However, on a fresh client (e.g. Incognito mode), if I immediately go to the iframe, I get the screen above. It seems, when navigating to the side panel first, it sets a cookie or similar but the same thing does not happen if I open the URL directly.

Any ideas?
