### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Antecer** [lovelylain/hass_ingress#7]
I just add this code:  

```yaml
ingress:
  add_ons:
    work_mode: ingress
    ui_mode: toolbar
    title: Add-ons
    icon: mdi:puzzle
    url: /hassio/dashboard
```

but when i click the icon, it show:  
502: Bad Gateway
