### ISSUE TITLE
How to add pve to panel

### ISSUE THREAD

**Issue by Antecer** [lovelylain/hass_ingress#8]
here is my configs:
```
ingress:
  pve:
    work_mode: iframe
    ui_mode: toolbar
    title: PVE
    icon: mdi:server-network
    url: "https://pve.local/"
```

the panel show like this:  
![image](https://github.com/lovelylain/hass_ingress/assets/8684916/33b32b07-a8a8-461d-ac8c-ebe0819f7a8e)

But the language can not change, it will refesh to default.
And when i login it, here do not show any kvm.
