### ISSUE TITLE
Basic authentication for work_mode: iframe

### ISSUE THREAD

**Issue by zecoj** [lovelylain/hass_ingress#9]
Hi,

I'm having issues with an iframe that has basic authentication, I tried both

`url: https://username:password@url.local
`
and 

```
url: https://url.local
headers:
  host: url.local
  authorization: Basic xxyyzz

```
But neither work.: 1st one: blank page, 2nd one: basic authentication pops up. Any idea?
